/**
 * JanNirikshan Status System Constants
 */

export const PROJECT_STATUSES = {
  ACTIVE: {
    key: 'ACTIVE',
    label: 'Active',
    color: 'emerald',
    bgClass: 'bg-emerald-50 text-emerald-800 border-emerald-300',
    dotClass: 'bg-emerald-500',
    iconName: 'Activity',
    description: 'Work is currently ongoing in accordance with project schedule.',
  },
  DELAYED: {
    key: 'DELAYED',
    label: 'Delayed',
    color: 'amber',
    bgClass: 'bg-amber-50 text-amber-800 border-amber-300',
    dotClass: 'bg-amber-500',
    iconName: 'Clock',
    description: 'Project milestone is behind official scheduled timeline.',
  },
  WORK_STOPPED: {
    key: 'WORK_STOPPED',
    label: 'Work Stopped',
    color: 'rose',
    bgClass: 'bg-rose-50 text-rose-800 border-rose-300',
    dotClass: 'bg-rose-500',
    iconName: 'AlertOctagon',
    description: 'Site activity has halted or been suspended by authority/contractor.',
  },
  NOT_STARTED: {
    key: 'NOT_STARTED',
    label: 'Not Started',
    color: 'slate',
    bgClass: 'bg-slate-100 text-slate-700 border-slate-300',
    dotClass: 'bg-slate-400',
    iconName: 'CircleDashed',
    description: 'Sanctioned or tendered, awaiting on-ground mobilization.',
  },
  COMPLETED: {
    key: 'COMPLETED',
    label: 'Completed',
    color: 'blue',
    bgClass: 'bg-blue-50 text-blue-800 border-blue-300',
    dotClass: 'bg-blue-500',
    iconName: 'CheckCircle2',
    description: 'Work has been executed and handed over for public usage.',
  },
};

export const OBSERVATION_STATUSES = {
  SUBMITTED: {
    key: 'SUBMITTED',
    label: 'Submitted',
    color: 'slate',
    bgClass: 'bg-slate-100 text-slate-800 border-slate-300',
    dotClass: 'bg-slate-500',
    description: 'Ground report received from citizen; queued for initial ingestion.',
  },
  UNDER_AI_ANALYSIS: {
    key: 'UNDER_AI_ANALYSIS',
    label: 'Under AI Analysis',
    color: 'indigo',
    bgClass: 'bg-indigo-50 text-indigo-800 border-indigo-300',
    dotClass: 'bg-indigo-500 animate-pulse',
    description: 'Computer vision and metadata validation pipeline currently processing evidence.',
  },
  UNDER_REVIEW: {
    key: 'UNDER_REVIEW',
    label: 'Under Review',
    color: 'amber',
    bgClass: 'bg-amber-50 text-amber-900 border-amber-300',
    dotClass: 'bg-amber-500',
    description: 'Assigned to authorized civic auditor or engineer for review.',
  },
  CORROBORATED: {
    key: 'CORROBORATED',
    label: 'Corroborated',
    color: 'teal',
    bgClass: 'bg-teal-50 text-teal-800 border-teal-300',
    dotClass: 'bg-teal-500',
    description: 'Multiple citizen reports or geotagged feeds affirm this observation.',
  },
  DISPUTED: {
    key: 'DISPUTED',
    label: 'Disputed',
    color: 'orange',
    bgClass: 'bg-orange-50 text-orange-900 border-orange-300',
    dotClass: 'bg-orange-600',
    description: 'Contradictory evidence exists between ground report and contractor status.',
  },
  VERIFIED: {
    key: 'VERIFIED',
    label: 'Verified',
    color: 'emerald',
    bgClass: 'bg-emerald-50 text-emerald-900 border-emerald-400 font-semibold',
    dotClass: 'bg-emerald-600',
    description: 'Confirmed by human authorized officer with official audit trail.',
  },
};

export const DATA_TIERS = {
  OFFICIAL: {
    key: 'OFFICIAL',
    name: 'Officially Published Information',
    badgeText: 'Official Public Record',
    styleTier: 'tier-official',
    colorTheme: 'navy-blue',
    icon: 'Building2',
    description: 'Data published by government agency, municipal corporation, or public works department.',
    seal: 'Government of NCT / Municipal Corporation Data Feed',
  },
  CITIZEN: {
    key: 'CITIZEN',
    name: 'Citizen Observation',
    badgeText: 'Ground Reality Observation',
    styleTier: 'tier-citizen',
    colorTheme: 'amber-slate',
    icon: 'Users',
    description: 'Unfiltered crowd-sourced observation submitted by a resident on site.',
    seal: 'Community Ground Witness Entry',
  },
  AI_ASSESSMENT: {
    key: 'AI_ASSESSMENT',
    name: 'AI-Assisted Assessment',
    badgeText: 'AI Automated Assessment',
    styleTier: 'tier-ai',
    colorTheme: 'indigo-purple',
    icon: 'Cpu',
    description: 'Preliminary automated computer vision & geospatial cross-check. Not official certification.',
    seal: 'Algorithmic Anomaly Detection (Beta)',
  },
  AUTHORIZED_VERIFICATION: {
    key: 'AUTHORIZED_VERIFICATION',
    name: 'Human / Authorized Verification',
    badgeText: 'Verified by Authorized Officer',
    styleTier: 'tier-verified',
    colorTheme: 'emerald-green',
    icon: 'ShieldCheck',
    description: 'Legally accountable sign-off by a designated municipal inspector or engineer.',
    seal: 'Empaneled Auditor Certified',
  },
};
